### PR TITLE
Create a LICENSE file to explicitly grant permission for code reuse.

### PR DESCRIPTION
**Pull request by Rosuav**
Requires approval from @devicat-outlet and @HallwayRaptor both for the legal permission to make the change, and the more minor details of how their names should be given.

### CODE REVIEW

**Comment by HallwayRaptor** [comment]
Approval from me!

**Comment by Rosuav** [comment]
Have been given permission from DeviCat via Discord. Merging.

**Comment by devicat-outlet** [comment]
Approval from me as well.

**Comment by Rosuav** [comment]
Thanks!

**Pull request merged**
